### ISSUE TITLE
Document what to do with custom-elements and other not-defined HTML tags (no-undef)

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-tooling/ember-eslint-parser#29]
Coming from: https://github.com/NullVoxPopuli/ember-eslint-parser/pull/28

Custom elements, including web components, are defined in global scope that are available, but not in local/file scope (unless explicitly defined).

There are two paths to informing eslint about new / custom globals:

In a single file
```js
/* global <my-var> */
```

and globally for the whole project:

```js
    {
      files: ['**/*.{gjs,gts}'],
      plugins: ['ember'],
      parser: 'ember-eslint-parser',
      globals: {
        // used in testing as a shorthand for <output>
        out: true,
        // used in the app
        // etc
      },
    },
```
the globals list will likely (and necessarily) be large for web-component users.

docs here: https://eslint.org/docs/latest/rules/no-undef

**Comment by patricklx** [comment]
We can add an option to disable the no-undef elements if you think that makes sense.

One could also define ember components that wrap those
```gjs
Out = <template> 
  {{#let (element 'out') as |out|}}
     <out \>
  {{/let}}
```
Or 
```gjs
WebComponent = <template> 
  {{#let (element @comp) as |comp|}}
     <comp ...attributes > {{tield}} </comp>
  {{/let}}
```
With gts one could also provide a list if components for auto completions.
Maybe also possible for attributes?

**Comment by NullVoxPopuli** [comment]
Those both feel like work arounds to the lint. Neither are needed in gts/glint, and natively being able invoke any HTMLElement (custom or not) is a big win of the templating system.

Making everything a FrameworkComponent i don't think is a pattern we want to encourage. Because we want to work with The Platform rather than wrap it, ya know?

**Comment by patricklx** [comment]
Yes, it should not be needed for lint. But i also see advantages for type checking with glint and auto completion .
So, is adding the globals to eslint good enough?

**Comment by NullVoxPopuli** [comment]
Glint currently doesn't have completion at all 😅 but it's not an ember feature to add it. As long as TS's global scope is configured correctly, all this sort of stuff can be used.

> adding the globals to eslint okay?

Ye

**Comment by Techn1x** [comment]
I've hit this as well. I sometimes use custom names for html tags to make the DOM a bit nicer
`<stat-box>...</stat-box>`

For now I'll add the `/* global <my-var> */` to each file but to me it would be nice if eslint would ignore custom html tags.

From memory (though I can't find any proof) custom tags should always be 2 words and dasherized (all single word tags are reserved) so maybe that can help?
